config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end

  resources :comments do
    resources :comments
  end


  devise_for :users
  root 'pages#index'
  get 'pages/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable
  
  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    if @comment.save
      redirect_back(fallback_location: root_path)
      flash[:success] = 'Comment successfully created'
    else
      flash[:error] = 'Something went wrong'
      render 'new'
    end
  end

  def destroy
    @comment = @commentable.comments.find(params[:id])
    if @comment.destroy
      flash[:success] = 'comment was successfully deleted.'
      redirect_back(fallback_location: root_path)
    else
      flash[:error] = 'Something went wrong'
      redirect_to post_path(@post)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_commentable
    if params[:post_id]
      @commentable = Post.find_by_id(params[:post_id])
    elsif params[:comment_id]
      @commentable = Comment.find_by_id(params[:comment_id])
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<li>
  <div class="card text-left">
    <div class="card-body">
      <div class="card-header">
        <%= comment.body %>
        <small>Submitted <%= time_ago_in_words(comment.created_at) %> ago</small>
        <%= link_to  "Delete", [comment.commentable, comment], method: :delete %>
      </div>
    </div>
  </div>
  

  <div class="card card-body mt-2">
  <%= form_for [comment, Comment.new] do |f| %>
    <%= f.text_area :body, class: 'form-control', placeholder: "Add a Reply" %><br/>
    <%= f.submit "Reply", class: 'btn btn-sm btn-primary'  %>
  <% end %>
  </div>

  <ul>
      <%= render comment.comments %>
  </ul>

</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorNgin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron bg-warning text-center mb-0 h-100 rounded-0 p-0">
  <div class="container-fluid h-100">
    <div class="row h-100">
      <div class="col-md-6 bg-danger h-100">
        <div class="h-100 d-flex flex-column justify-content-center">
          <h1 class="display-1 font-weight-bolder">Welcome</h1>
          <h3>to</h3>
          <h1 class="display-1 font-weight-bolder text-warning">rormaster</h1>
           <p>rormaster is a rails 6 starter template.</p>
        </div>
      </div>
      <div class="col-md-6 bg-white h-100">
        <div class="h-100 d-flex flex-column justify-content-center"
          <p>Included Resources</p>
          <div class="resources">
            <span class="badge badge-danger rounded-0 font-weight-bold p-2 mb-1">Bootstrap-4</span>
            <span class="badge badge-danger rounded-0 font-weight-bold p-2">jquery</span>
            <span class="badge badge-danger rounded-0 font-weight-bold p-2">popperjs</span>
            <span class="badge badge-danger rounded-0 font-weight-bold p-2">font-awesome-5</span>
            <span class="badge badge-danger rounded-0 font-weight-bold p-2">Devise</span>
          </div>

          <div class="button_container mt-5">
            <% if user_signed_in? %>
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger rounded-0' %>
              <%= link_to "Posts", posts_path, class: 'btn btn-outline-success rounded-0' %>
            <% else %>
              <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-outline-danger rounded-0' %>
              <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-outline-danger rounded-0' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: 'btn btn-sm btn-outline-success' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row d-flex justify-content-center mt-5 pt-5">
    <div class="col-md-8">
      <h1>Editing Post</h1>

      <%= render 'form', post: @post %>

      <%= link_to 'Show', @post %> |
      <%= link_to 'Back', posts_path %>
    </div>
  </div>  
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.user_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<div class="container">
  <div class="row d-flex justify-content-center mt-5 pt-5">
    <div class="col-md-8">

<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

    </div>
  </div>  
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row d-flex justify-content-center mt-5 pt-5">
    <div class="col-md-8">
      <div class="card card-body">
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Title:</strong>
          <%= @post.title %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @post.description %>
        </p>

        <p>
          <strong>User:</strong>
          <%= @post.user_id %>
        </p>

        <%= link_to 'Edit', edit_post_path(@post) %> |
        <%= link_to 'Back', posts_path %>
      </div>
    </div>
  </div>



  <div class="row d-flex justify-content-center mt-5 pt-5">
    <div class="col-md-8">
      <div class="card card-body bg-success mb-5">
        <h3>Add your comment</h3>
        <%= form_for [@post, Comment.new] do |f| %>
          <%= f.text_area :body, class: 'form-control', placeholder: "Add a comment" %><br/>
          <%= f.submit "Add Comment", class: 'btn btn-sm btn-primary' %>
        <% end %>

        <hr>
        <h3>All Comments</h3>
        <ul class="nested-comments">
          <%= render @post.comments %>
        </ul>
      </div>
    </div>
  </div>
</div>